### ISSUE TITLE
Reference-based RNA seq: To improve

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1006]
To do list after the workshop in Freiburg (mostly comments from @pavanvidem)
- [ ] Rename files to `_R1` and `_R2`
- [ ] Re-add the `Annotate DESeq` step
   - [ ] Add it to the MTS (@pavanvidem ?)
- [ ] Make the input stranded?
- [ ] Make the join step less confusing: maybe with more than 1 step
- [x] Add "counts" in FeatureCounts file name (in the tool) PR for this here: https://github.com/galaxyproject/tools-iuc/pull/2103

Comments
- "Infer experiment" did not need a BED12 before

**Comment by nsoranzo** [comment]
> Make the join step less confusing: maybe with more than 1 step

@bebatut @pavanvidem I think this refers to step 1 of the "Hands-on: Extract the normalized counts of the 20 most differentially expressed genes". I tried it yesterday and this generates a broken tabular dataset because the filtered DESeq2 result dataset has the column headers as metadata, while the normalized counts file has them as first row.
Any idea how to solve this?

**Comment by mblue9** [comment]
Btw that title ""Hands-on: Extract the normalized counts of the 20 most differentially expressed genes" needs updating as it used to be the top 20 but now it seems to be 130.

>"Infer experiment" did not need a BED12 before

I ran into this issue at GCC, apparently there used to be a converter that auto-converted the GTF into BED so that step wasn't needed. Afaik it doesn't work anymore but that may have changed.

**Comment by nsoranzo** [comment]
> Btw that title ""Hands-on: Extract the normalized counts of the 20 most differentially expressed genes" needs updating as it used to be the top 20 but now it seems to be 130.

@mblue9 Addressed in https://github.com/galaxyproject/training-material/pull/1022 .

**Comment by pvanheus** [comment]
Notes as I'm going through:

0. intend to add demo of using scratchbook for comparing sorted feature counts
1. on the join datasets problem: copy the header line from the last Filter, paste it as a Pasted Entry (the "upload tool", concatenate it with Filter output, then join
2. at the stage where one is to Change case of "From”: the feature lengths (output of featureCounts tool)", you only need one and it can come from the previous analysis or be dragged across if you are using a new history.
