### ISSUE TITLE
Offer makefile to compile slides to PDF

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#103]
It would be nice to offer a makefile to compile all slides to PDF and maybe other nice things to help training developers.

**Comment by blankclemens** [comment]
There are some easy steps to create a pdf out of the reveal.js slides, the question is: Where to put this information? In the main README? Steps are:

1. Include the `print-pdf` tag in the slide adress, e.g. [http://bgruening.github.io/training-material/RNA-Seq/slides/ref_based.html?print-pdf](http://bgruening.github.io/training-material/RNA-Seq/slides/ref_based.html?print-pdf)
2. Open the print dialog (CTRL/CMD+P) and set the destination to **Save as PDF**.
3. Change the Layout to **Landscape**, the Margins to **None** and enable the **Background graphics** option before saving.

**Comment by bebatut** [comment]
There is even an easier way. Using [Decktape](https://github.com/astefanutti/decktape/tree/328e4438189c2f9a12dcc548a4a9b8557bdb59b5). It can then be done using Travis.

**Comment by stevekm** [comment]
which slides are you trying to compile?

**Comment by bgruening** [comment]
All reveal.js slides we have created or we will create :)

**Comment by shiltemann** [comment]
should we consider also allowing remarkjs slides? It is not as spiffy as reveal, but you write your slides in pure markdown, no HTML, making them easier to write for a lot of people, and what I really like is that you can easily view them by prepending http://htmlpreview.github.io/? to your github file, so you don't have to serve them anywhere

for example, my slides here:
https://github.com/ErasmusMC-Bioinformatics/galaxy-courses/blob/master/Galaxy101/Galaxy101_slides.html

can be viewed simply by prepending this prefix to the url:
http://htmlpreview.github.io/?https://github.com/ErasmusMC-Bioinformatics/galaxy-courses/blob/master/Galaxy101/Galaxy101_slides.html

though come to think of it, this might be possible with reveal.js as well if we link directly to the source files instead of via the submodules, don't know, that at least would be nice to investigate?

it is nicer to have a single style of course, but my slides are often simple, no fancy transitions or multidimensional paths needed for me ;) so I don't really need the full power of reveal.js a lot of the time.. (but that may just be me ;P)

**Comment by blankclemens** [comment]
Fyi: There is a Makefile in the root directory now which let's you create PDF's of all or single slides using decktape. See #124

**Comment by jmchilton** [comment]
@shiltemann I agree with this completely. This is a strategy I am pursuing in Galaxy core (https://github.com/galaxyproject/galaxy/pull/2283) and Planemo (https://github.com/galaxyproject/planemo/blob/master/docs/galaxy_changelog.md | http://planemo.readthedocs.io/en/latest/galaxy_changelog.html). Using Markdown for slides allows direct integration with documentation such sphinx and enable direct reuse between long form docs and slide-based docs.

**Comment by friedue** [comment]
yesssss, markdown for the win!!!!

**Comment by bgruening** [comment]
As a reference: https://github.com/bgruening/training-material/issues/8

**Comment by bgruening** [comment]
@jibe-b you might want to present your work and our discussion about the template-engine integrated in markdown.

**Comment by stevekm** [comment]
@shiltemann on Chrome mobile I can't seem to navigate through your slides past the first page.

Also for what it's worth, isn't there a way to compile Markdown into beamer?

**Comment by stevekm** [comment]
Yes I think this is it, haven't tried it yet though

http://rmarkdown.rstudio.com/beamer_presentation_format.html

**Comment by bgruening** [comment]
@stevekm markdown can be converted to everything also beamer and latex.

**Comment by jibe-b** [comment]
Reavealjs is not the easiest library for markdown to slides conversion.

Yet, it is possible to convert a markdown file (like a tutorial) to slides, keeping only titles and indicated content in the slides.

In [this fork](https://github.com/jibe-b/training-material/tree/add-markdown_to_reveal) in the submodule _markdown_to_reveal_ there is a script to produce slides from a tutorial marklown file at the cost of some syntax care (see the README.)

See #132 for a proposition to consider markdown source of tutorials as a main source for both texts and slides.

**Comment by martenson** [comment]
@shiltemann even better than htmlpreview is `https://remarkjs.com/remarkise?url=<path.to.md>`

**Comment by willdurand** [comment]
Done in #448.
