### ISSUE TITLE
Generate PDFs of trainings with only hands-on boxes

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#1065]
Can we generate a PDF with only the hands-on steps - tools and parameters?

**Comment by nsoranzo** [comment]
Use case?

**Comment by nsoranzo** [comment]
If the handouts are to keep as a reference after the course, then without the explanations they are not very useful. If they are to be used during the course, I think they can be more of a distraction (trainees will just do what's on the handout without listening and/or understanding).

**Comment by bgruening** [comment]
Afaik the use-cases we talked about were:

* have a simply cheat-sheet for instructors if you don't have two monitors (one Galaxy, one training-material)
* have a simple summary for people running around and helping - they very often needs to check parameters and such

**Comment by hexylena** [comment]
generating those PDFs regularly would be expensive (since it requires chrome-headless), so I think this is not a priority currently, since it's just wasting CPU time to constantly rebuild them, if no one is using them regularly.

We could merge this https://github.com/galaxyproject/training-material/compare/onlyhandson?expand=1  and have a URL parameter if you like?
