### ISSUE TITLE
materials are linked using unsecure protocol

### ISSUE THREAD

**Issue by martenson** [galaxyproject/training-material#1086]
Whatever topic I click on from (secured) page https://galaxyproject.github.io/training-material/ will be accessed only with `http` including any links to subsequent content. This seems unfortunate given all the pages support https. We should promote only https links. 

We should also redirect automatically if possible.

**Comment by erasche** [comment]
maybe it would be useful to have a "training-material" admigithub team

**Comment by willdurand** [comment]
Looks like a 301 is being sent somehow, that's weird (and bad).

**Comment by martenson** [comment]
I turned on enforcing https. Apart from some mixed-content warnings (external http images) it seems to work as intended?

@willdurand What do you mean?

**Comment by willdurand** [comment]
`301` redirects are persistent. The problem is that now, most clients will remember to redirect HTTPS links on the homepage to their HTTP equivalent links.

Because you turned HTTPS on on GitHub, it gets redirected again. That's why it works, not exactly because links got fixed (I still believe it is the proper fix, although it is odd that relative links were not reusing the current protocol).

Anyway, a picture is worth a thousand words:

![screen shot 2018-10-12 at 15 52 04](https://user-images.githubusercontent.com/217628/46955153-8d58a680-d092-11e8-8041-f0391f70c169.png)

**Comment by martenson** [comment]
>although it is odd that relative links were not reusing the current protocol

yep, that confused me as well
