### ISSUE TITLE
admin training GCC2019 notes

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/training-material#1436]
Feel free to add your comments here: 

- [x] `You are installing ansible on a machine that will manage a second, remote machine` #1437 

    Having a second path here seems to violate the one true path rule... 

    Also if you shutdown/reset these machines then the motivation from the beginning would not work.

- [x] When choosing to run ansible on a remote host, login should be mentioned, ie set up ssh loging w/o password or store the password somewhere. 

    Or: `ansible-playbook -i hosts playbook.yml -k`

- [x] `api_key = {{ my_role_key }}` this might be a good place to mention/introduce the vault

**Comment by erasche** [comment]
Documenting the second method for ansible connection is because it is quite normal. I personally encourage admins to run the playooks from their local computers, but this is a *huge* issue during training: people have windows/etc, and installing ansible does not work. 

We have the "one true galaxy path", but not the "one true ansible path"

> if you shutdown/reset these machines

Yes, this is why I encourage people to keep their ansible setups locally/in git. It is not disaster proof to have it on the machine. But this again does not work easily with training.

> mention how to connect

You're right, that's not mentioned. It used to be.

**Comment by bernt-matthias** [comment]
I agree. But it might be better to choose a single path for the training (might be sufficient to mention it in the training), because I'm sure that in every training there is someone like me that chooses the other option and will get lost.

**Comment by erasche** [comment]
That could be, always resisted removing that because it's the wrong way to do things in production, but I think you're right in the end, too confusing for no benefit.

**Comment by bernt-matthias** [comment]
I'm definitely pro keeping it as well. Would be sufficient to:

- the trainer should just mention which path should be followed and 
- docs for the remote path should be completed

**Comment by erasche** [comment]
- [ ] lockout on wiping out directories if playbook is currently running. `pgrep ||`

**Comment by erasche** [comment]
Implemented all things in PR #1445, closing this now so I won't forget.
