### ISSUE TITLE
analysing PCA scatter plot using galaxy project training material

### ISSUE THREAD

**Issue by jahid10** [galaxyproject/training-material#1962]
![Screenshot_3](https://user-images.githubusercontent.com/65849689/87219402-8ac8d500-c37c-11ea-94bd-791ad7f4d184.jpg)
I have generated PCA graph from md simulation trajectories using your training material. I don't seem to completely understand the plot. There are some semi-transparent dots along with deep blue and red dots what does they signify (semi-transparent dots)

**Comment by chrisbarnettster** [comment]
Hi @jahid10 
Will you send a link to the tutorial you were using so that I can make the update here? 

The dots signify sampling in the principal component space. For example in the graphs you sent in, this is the sampling of PC2 vs PC1. These dots are colored from blue to red in order of time using a Blue-Red diverging color palette ([further details](http://thegrantlab.org/bio3d/tutorials/trajectory-analysis). Light blue, white and light red dots represent sampling near the middle of the trajectory. 

You will also be able to use a scree (or eigenvalue rank plot) where the cumulative variance is plotted for each principal component. This plot assists in determining the number of principal components to keep.

**Comment by jahid10** [comment]
Thanks , that actually helped me understand the problem I had describing my
plot!
The link to the tutorial has given below
https://galaxyproject.github.io/training-material/topics/computational-chemistry/tutorials/analysis-md-simulations/tutorial.html
Have a great day

**Comment by hexylena** [comment]
Question seems to be answered, please re-open if not.
