### ISSUE TITLE
More options for acknowledging contributions on tutorials?

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/training-material#2015]
In line with a [all-contributors](https://github.com/all-contributors/all-contributors) type model, it would be good to be able to specify the kind of contribution made to training material by the different people listed. This could also help clarify what "contribution" is. 

A possible technical mechanism is to allow the `contributors` key to accept a list of maps, with name and contribution type.

**Comment by hexylena** [comment]
Interesting, hadn't heard of that! Since we're science oriented, we could also consider [SCoRO](https://sparontologies.github.io/scoro/current/scoro.html) or similar?

**Comment by hexylena** [comment]
https://allcontributors.org/docs/en/emoji-key I think we might want to come up with our own emoji key because those don't cover the full set of cases. but let's revive this maybe in the linked discussion, I want to see something like this happen.

Updating the `contributors` key would be easy, just instead of 

```
contributors:
- hexylena
- shiltemann
```

We could replace it with

```
contributors:
  shiltemann: [writing]
  hexylena: [spell-checking, copy-editing, testing]
```

or so.

**Comment by hexylena** [comment]
I've opened a discussion https://github.com/galaxyproject/training-material/discussions/2986 here that's related

**Comment by hexylena** [comment]
Ok, our own categories for contribution could be: (writing down for my memory since @shiltemann and I had a discussion in person a while back and I already forgot it :woman_facepalming: )

- :pencil2: writing / authorship
- :memo: copy-editing (spell-checking, typos, very small fixes?)
- :gear: testing
- :nail_care: layout/design?
- :desktop_computer:  infrastructure / sysadmin / github actions editing / etc

**Comment by hexylena** [comment]
https://eos.org/opinions/credit-where-credit-is-due
https://groups.niso.org/higherlogic/ws/public/download/26466/ANSI-NISO-Z39.104-2022.pdf
https://www.ebi.ac.uk/ols/ontologies/cro
https://ddialliance.org/
