### ISSUE TITLE
Duplicated tutorial?

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/training-material#2403]
[Multisample Analysis](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/processing-many-samples-at-once/tutorial.html) and [Using dataset collections](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html) are practically identical.

**Comment by wm75** [comment]
When working on this, please treat https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html as the reference. Check the other one if it contains anything missing from the reference, and if so try to integrate it into it.
In the end, we want to keep the reference with as few changes as possible since this has been updated very recently.

**Comment by TheKharleeci** [comment]
Ok. Noted

**Comment by TheKharleeci** [comment]
I just made a pull request @shiltemann
