### ISSUE TITLE
Galaxy papercuts CoFests form needs an update 

### ISSUE THREAD

**Issue by otatadeabigail** [galaxyproject/training-material#2867]
The form says the next event is April 15th, 2021.
The date needs to be updated.
https://docs.google.com/forms/d/e/1FAIpQLSc-OUa9s-L9DO1RMuSeiOWts1am0eWXI9VKM9dHfKxExBS-ag/viewform

**Comment by beatrizserrano** [comment]
Hi @otatadeabigail. Thanks for reporting, we need to take that form offline because it belongs to an old event (we are hosting Papercuts every month for a year now! 😺). The details for Papercuts this Thursday are here:

https://galaxyproject.org/events/2021-10-papercuts/

I will then close this issue as this is unrelated to the Galaxy Training Network.
