### ISSUE TITLE
make top navbar of Galaxy training UI fixed to top when page scroll

### ISSUE THREAD

**Issue by saritadc** [galaxyproject/training-material#2971]
While using the Galaxy training website, I came across that the top navbar is not fixed when we scroll the page and when I'm at the end of the page I have to scroll all the way up to the top to the navbar. I want to work on this. @bebatut can you have a look at this issue?

![image](https://user-images.githubusercontent.com/24495393/139835253-2f850f8f-d3af-451c-ae22-dededaea4467.png)

**Comment by hexylena** [comment]
Hi @saritadc, this was an intentional decision for us

1. A lot of our GTN readers access the site via mobile, and a navigation bar would take up a lot of vertical space
2. But more importantly, users very very rarely need to access the menu bar. The extras/search/topic buttons are rarely useful for readers. Most students read the tutorial top to bottom and don't stop in the middle to search the GTN for other tutorials or so.
