### ISSUE TITLE
GTN Feedback page:  Links needed for each item under topics

### ISSUE THREAD

**Issue by Ahuoyiza** [galaxyproject/training-material#2987]
# What is the issue?

The GTN feedback page currently only links back to the topics. The specific tutorial(s) that got feedback doesn't have a direct link to it and this makes it difficult for contributors to easily access the said tutorial and address issues.

# Suggestion
1. ~~In the form, users can be asked to drop a link to the tutorial they are giving feedback  or~~
2. ~~We automate form submission to store source URL~~

# Benefits:
1. Contributors will easily link back to tutorials with feedbacks
2. Fix time will be reduced

**Comment by hexylena** [comment]
> In the form, users can be asked to drop a link to the tutorial they are giving feedback or

This is already done, and automated! It's hidden in the form so it isn't visible to users and they can't accidentally change it. This line includes the tutorial + topic title: https://github.com/galaxyproject/training-material/blob/main/_layouts/tutorial_hands_on.html#L268

And you'll see in our feedback.csv file that's in the repository we have columns for both the tutorial + topic, so, it should all already be connected. https://github.com/galaxyproject/training-material/blob/main/metadata/feedback.csv 

But I'm worried I misunderstand your suggestions section? Because you correctly point out that in the feedback page (e.g. https://training.galaxyproject.org/training-material/feedback.html#tutorial-unicycler-assembly) it is missing a link to the specific tutorial

**Comment by Ahuoyiza** [comment]
Oh, since the form is automated to do that already, then that won't be necessary as a suggestion.

But yes, the existing issue is the missing link to tutorials 
[Quick issue demo here](https://www.loom.com/share/a66e7eab113a4611852b0bc9ac8f55f0)
