### ISSUE TITLE
[FAQs] Data upload sub FAQs not displayed on the left panel.

### ISSUE THREAD

**Issue by garimavs** [galaxyproject/training-material#3442]
This issue is to mention that the sub FAQs under [Data Upload](https://training.galaxyproject.org/training-material/faqs/galaxy/#data%20upload) are not displayed on the left panel.

![image](https://user-images.githubusercontent.com/77723358/165834572-7e5b2ec3-6e29-4228-8e73-490169ada97e.png)

**Comment by garimavs** [comment]
Two FAQs under this area: [Importing data from a data library](https://training.galaxyproject.org/training-material/faqs/galaxy/datasets_import_from_data_library.html) and [Importing via links](https://training.galaxyproject.org/training-material/faqs/galaxy/datasets_import_via_link.html) are pretty old, and I worry if renaming those will again cause issues like broken links.

Will it be wise to go forth with this issue?
Kindly suggest!

**Comment by hexylena** [comment]
Please don't rename them, that is not the right way to fix this. We would very much like to keep the filenames that they have now.

Instead this should be fixed in the template. https://github.com/galaxyproject/training-material/blob/main/_layouts/faq-page.html

I'm not sure how to best advise you here, it's a lot of liquid templating that's a bit complex.

**Comment by garimavs** [comment]
By renaming I didn't mean to rename the FAQ 😅 
A similar case as this one is in this [PR](https://github.com/galaxyproject/training-material/pull/3443)
And I was thinking to do the same with this issue too.

**Comment by shiltemann** [comment]
I think this is fixed now, thanks for reporting!
