### ISSUE TITLE
Filling out contributions metadata breaks tutorial citations

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/training-material#3564]
Filling out contributions metadata (i.e., detailing how folks contributed) breaks the citations at the bottom of the tutorial: no authors are listed ([here's just one example](https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible-galaxy/tutorial.html#citing-this-tutorial)).

Fixing this might raise further questions: it's one thing to be listed as a contributor on the web page, it's another to be listed as an author in the citation. I don't think there's a format for differentiating type of contribution in a citation: everyone is a co-author. Also whom do we "et al" when there are too many?

**Comment by hexylena** [comment]
Ahh good catch, I hadn't yet found all the places we have if-casing around the two different styles of authorship. That's relatively easy to fix. (those citations also aren't heavily used i suspect)

For the detailed authorship format we'd probably list authors as authors, and everyone else just as 'et al', rather than listing every single person.

**Comment by hexylena** [comment]
oh right et al is automatic by bibtex, then ok just leave it out.
