### ISSUE TITLE
CONTRIBUTING file is out of date and has dead links

### ISSUE THREAD

**Issue by martenson** [galaxyproject/training-material#362]
I am starting a new set of materials. Following the current CONTRIBUTING is almost impossible as many links are dead and the structure of the repo has also changed compared to what this file refers to.

https://github.com/galaxyproject/training-material/blob/master/CONTRIBUTING.md

**Comment by bebatut** [comment]
With the ongoing migration to the new templating system, we tried to keep up-to-date the `CONTRIBUTING.md` (at least for the tutorials) but we missed some changes (the workflows and tours directory for example). I will try to fix that. If you see something else, can you tell me, please?
And the migration is still ongoing, so it can change again... Sorry for that.

Can you also tell me which links are dead? I will try to fix them.

Otherwise, I started to write a tutorial to explain how to write a [tutorial](https://github.com/galaxyproject/training-material/blob/training_topic/topics/training/tutorials/create-new-tutorial/tutorial.md). It is a very first draft, but any feedback is welcome :)

**Comment by willdurand** [comment]
Fixed?

**Comment by bgruening** [comment]
Should be, @martenson please feel free to reopen.
