### ISSUE TITLE
[Reference-base RNA-seq] Broken question / answer boxes 

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#3752]
![image](https://user-images.githubusercontent.com/1842467/201305564-de88ccca-5293-4962-919c-9488363ea1d1.png)

**Comment by shiltemann** [comment]
yeah these are all boxes in `{% includes %}` and happens due to the order in which jekyll processes things, seen it in other places, not an easy one..

I think for a quick fix, we can either revert to the old-style box syntax for these includes, or turn them into proper faqs (and use `{% snippet %}` to include them ..might be nice to have them on the FAQ page anyway, and if some tutorial-specific things are used in them (such as file names), maybe can make that variable-based

**Comment by shiltemann** [comment]
xref https://github.com/galaxyproject/training-material/issues/3684
