### ISSUE TITLE
Circos training: problem in Presidential Debate plot

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/training-material#3952]
An user reported that, when trying to generate the plot by using the debate_karyotype.txt file, Galaxy shows that error:

`Can't call method "colorExact" on an undefined value at /usr/local/tools/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Colors.pm line 348, <F> line 7.`

I think it can be fixed by replacing with the following content:

```
chr - obama OBAMA 0 2000 FF0000
chr - richardson RICHARDSON 0 1000 FF0000
chr - clinton CLINTON 0 1500 FF0000
chr - mccain MCCAIN 0 1000 0000FF
chr - romney ROMNEY 0 1750 0000FF
chr - huckabee HUCKABEE 0 1250 0000FF
```

**Comment by hexylena** [comment]
@gallardoalba which version of the tool was this? Most issues for "colorExact" were for the older version of the tool wrapper that is selected by default because Galaxy can't sort `+galaxy` versions properly. If you're on `+galaxy10` and still have this issue, please feel free to share the history or so.

@erxleben reported to me a similar issue, there was an issue in the wrapper. I'm going to open a PR soon.

**Comment by hexylena** [comment]
You're using galaxy9, can you please check with galaxy10?

**Comment by gallardoalba** [comment]
Yes, when using Galaxy10 it worked correctly. Thanks!
