### ISSUE TITLE
Why is the tutorial "Under Development"

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/training-material#4406]
Hi all, 
I just found out that our tutorial is under development and I don't know why, it was already published as being ready quite some time ago: 
https://training.galaxyproject.org/training-material//topics/proteomics/tutorials/maxquant-msstats-tmt/tutorial.html
Thank you,
Melanie

**Comment by hexylena** [comment]
This looks like it was a mistake, [I batch replaced](https://github.com/galaxyproject/training-material/commit/f0c09cdd6db7f8bb03fe3eb7666844992c6f0a00) `enable: false` to `draft: true`, but also seem to have mistakenly included your tutorial, which was the only one to include `enable: true` (most people just removed the key, rather than setting it to true)

**Comment by hexylena** [comment]
Will be fixed in https://github.com/galaxyproject/training-material/pull/4407 if you can approve/merge that :)
