### ISSUE TITLE
Imaging introduction (workflow) uses non-existent tool

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/training-material#4469]
The workflow for the tutorial uses `toolshed.g2.bx.psu.edu/repos/imgteam/overlay_segmentation_mask/ip_overlay_segmentation/0.0.6` [here ](https://github.com/galaxyproject/training-material/blob/e6fda7bf33d4162d693c257dff7ab6b13cac6485/topics/imaging/tutorials/imaging-introduction/workflows/Galaxy-Workflow-GTN_Tutorial__Introduction_to_Imaging.ga#L326)

Searching the TS only yields  https://toolshed.g2.bx.psu.edu/view/imgteam/overlay_images/b74693340624 

Tool ID and name fit, but repo name seems wrong also the workflow uses a newer version than available in the TS.

Oddly importing the workflow on eu gives no error/warmning.

**Comment by hexylena** [comment]
@thomaswollmann @shiltemann @kostrykin

**Comment by kostrykin** [comment]
Is it [this tutorial](https://usegalaxy.eu/training-material/topics/imaging/tutorials/imaging-introduction/tutorial.html) which you are referring to? @bernt-matthias 

I don't know what happened to "old" tool, but I [fixed](https://github.com/galaxyproject/training-material/commit/15e4f5641becf06101a3eb4309e9fbb18b2121c4#diff-cc0c32608fce527498a59f0bb429ec177bf1800dab23bf1f4a8add0307efff97) the tutorial a few months ago, so that the correct "new" tool is in place (see 15e4f56). However, I wasn't aware that the `.ga` files also needs to be updated. I will have a look at that.

**Comment by hexylena** [comment]
Thanks so much @kostrykin !
