### ISSUE TITLE
Allow for `or` in workflow query

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/training-material#4494]
The GTN hosted workflow query like: https://training.galaxyproject.org/training-material/workflows/embed.html?query=microbiome is useful to select dedicated workflows for a community, would it be possible to add `or` as an option to fine grain the query possibilities, similar to e.g. `query=microbiome+longreads`.

**Comment by hexylena** [comment]
We'll look into this! Do you envision needing `and` support as well? because I'm guessing `longreads` might return a lot of non-microbiome results.

**Comment by paulzierep** [comment]
isn't my example an 'and' query ?

**Comment by hexylena** [comment]
Ah ok, then the converse, do you see needing an `or` query?

**Comment by hexylena** [comment]
Ok, then I'm hearing that we need both. We'll have to see what we can do in terms of syntax!

**Comment by paulzierep** [comment]
As I understand it `and` does already work, try e.g. https://training.galaxyproject.org/training-material/workflows/embed.html?query=microbiome+nanopore

**Comment by hexylena** [comment]
It definitely wasn't explicitly implemented :sweat_smile: hence my confusion. `microbiome+nanopore` is interpreted as `microbiome nanopore` ([since + is treated as space](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#preserving_plus_signs)), it's a complete accident that you're seeing any useful results, because we've put together a couple different fields including tags, which we do a simple text index match against (i.e. no fuzzy query, terms aren't treated separately, etc.)

I'm guessing you'd find more results if it was doing a proper `and` so, ok, we'll implement both.

**Comment by paulzierep** [comment]
ah ok, now both our confusion finds an end :) in this case both an `and` and `or` would be nice to have
