### ISSUE TITLE
101 for everyone: history sharing clarifications

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/training-material#4547]
In the last part of the tutorial there are statements which could need a bit of clarification:

> Different servers have different default permission settings. Some servers create all of your datasets completely private to you, while others make them accessible if you know the secret ID.

- How can I know as a user the  default permission settings of the server
- What is the secret ID?

> Be sure to select Also make all objects within the History accessible whenever you make a history accessible via link, otherwise whomever you send your link to might not be able to see your history.

- Cant find a checkbox `Also make all objects within the History accessible ` when sharing. 

Is this now in the `Set permissions` item of the history menu? What is the meaning of selecting no user there?

**Comment by hexylena** [comment]
> How can I know as a user the default permission settings of the server

would be great if galaxy made that more obvious 

secret id here meaning the link to the history with the id, rather than a slug. I'm not sure if this is still relevant information.

> Is this now in the Set permissions item of the history menu? What is the meaning of selecting no user there?

this might have been fixed on the galaxy side. previously there were some issues because only eu set private datasets by default. but I suspect that's gotten better. we should recheck this, thanks for raising it.
