### ISSUE TITLE
GTN dark mode clarification

### ISSUE THREAD

**Issue by hujambo-dunia** [galaxyproject/training-material#4572]
Just one person's opinion, minor suggestion to not make the default the OS user's system dark/light-mode setting but just to make default light-mode (maybe a notification instead just saying there's a new feature?). One day my screen went from light to dark mode and I couldn't figure out why (and did not like the dark mode option in this instance unfortunately).

<img width="1283" alt="Greenshot 2023-12-05 14 10 06" src="https://github.com/galaxyproject/training-material/assets/3672779/67db962d-55be-4f84-8582-52ac4d925308">

**Comment by nekrut** [comment]
I'll second that. Dark mode is not visually appealing to me personally.

**Comment by hexylena** [comment]
> Just one person's opinion, minor suggestion to not make the default the OS user's system dark/light-mode setting

The alternative view (that we're responding to) is that the user _specifically requested_ dark mode. They made a browser preference choice on a laptop/desktop, or in the case of mobile devices, an OS-level choice to request dark mode from every application and website they interact with; we're just honoring their request as fully as possible.

> but just to make default light-mode (maybe a notification instead just saying there's a new feature?). 

from my side I don't feel _terribly_ keen to force people into a light mode interface (blinding at night), this is the safer choice that still lets them choose their preference afterwards.

We wrote a blog post about the [new user preferences menu](https://training.galaxyproject.org/training-material/news/2023/07/20/prefs.html) when we made that change but perhaps it should've been more explicit? We can make a new one and if you have other suggestions for notifying the user or guiding them to this preference I'm very open to it!!!

I can 100% agree the preferences menu is not super easy to find, thanks to the unusual masthead menu structure of the GTN (i.e. there's no "user account") so it's under "Extras" which is absolutely not the most obvious place to look.

We've been considering a potential future redesign someday and that will absolutely have a more user-like menu, but until then I'm open to all options! 

We could have a first visit popup in the home page indicating this (but that's a lot of very important screen real-estate, we'd have to be sure of how we want to display it.)

> One day my screen went from light to dark mode and I couldn't figure out why (and did not like the dark mode option in this instance unfortunately).

I'm sorry about the unexpected change! But previously there wasn't a good way to decide who wanted light mode, actively was requesting that, vs otherwise. So we defaulted to "what the user requested via their browser/os".

You can change it at any time in the user preferences view, and now change even more aspects of the theming here: https://training.galaxyproject.org/training-material/preferences.html

The theme options should be quite extensive, and are somewhat modeled after GitHub's in that we have separate options for light and dark, high and low contrast, and let the user prefer one of these or just to use them automatically.

**Comment by hexylena** [comment]
After some discussion with @shiltemann would you both @nekrut @hujambo-dunia find this a more obvious place to look?

![image](https://github.com/galaxyproject/training-material/assets/458683/ce245637-8661-4d02-9dce-e3cf25fecf17)
