### ISSUE TITLE
Switch to Less + shared style lib

### ISSUE THREAD

**Issue by willdurand** [galaxyproject/training-material#464]
Follow-up #463 

The plan is to get a stable and published version of this package: https://github.com/jxtx/galaxy-bootstrap (will likely move to another namespace) and to pull it into this repo, leveraging a uniform/consistent Galaxy style.

**Comment by erasche** [comment]
The linked repository is quite out of date relative to hub and to current styling of Galaxy, unfortunately. I guess they have abandoned that effort as well. If it gets renewed, then maybe it becomes interesting again to look into doing this, otherwise maybe it is OK for the training material's styling to deviate in places from Galaxy's? So maybe we also give up on this for now? Let's re-open if galaxy looks like they're moving in this direction.
