### ISSUE TITLE
js bundle not loaded in devlopment

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/training-material#4897]
Hi,

Super minor issue.

I was trying out the gtn repo locally. When the jeklyll env is development the js bundle (main and theme) are not loaded but individual js files (e.g for jquery and bootstrap)  are loaded with individual script tags. But I get jquery not available errors in firefox due to it being loaded after bootstrap. So the popups (e.g to expand tip boxes) don't work.  
Setting jekyll env to production fixes this. 
Thanks!

**Comment by hexylena** [comment]
I will fix it. Apologies for the inconvenience

**Comment by hexylena** [comment]
I believe it is down to `async defer`, that on subsequent page loads the popups do seem to work. We set that to defer loading of non-critical javascript in production (popups aren't strictly necessary for most functionality) but there it works because all of the JS is bundled. However locally it is not, so async and defer lets the JS get loaded out of order causing issues with jquery.

**Comment by hexylena** [comment]
Should be fixed by https://github.com/galaxyproject/training-material/pull/4899
