### ISSUE TITLE
Enable event listing on funders page

### ISSUE THREAD

**Issue by teresa-m** [galaxyproject/training-material#5231]
It would be great to list on the hall of Fame page of each funder the events, which were funded.

To be more precise it would be nice if a page like this: https://training.galaxyproject.org/training-material/hall-of-fame/biont/

In addition to training and slides also the events funded would be listed.

**Comment by hexylena** [comment]
![image](https://github.com/user-attachments/assets/d6c6b5a2-f960-4a11-a40e-752aaf44039a)

this was implemented before gcc :) https://github.com/galaxyproject/training-material/commit/10903f15baee916dfa30030ee519850c917484cc

**Comment by bgruening** [comment]
Cool, thanks @hexylena

**Comment by teresa-m** [comment]
@hexylena: Thanks so much! A general question. Events linked with an external event page are not listed at the moment at least for the BioNT events. Is this by intention?

**Comment by hexylena** [comment]
I wouldn't say intentional, rather we did not expect external event users to ever want to annotate funders, they generally have external mechanisms for getting that credit. it would of course be possible to include external events on that page, provided they're marked up

https://github.com/galaxyproject/training-material/blob/main/_plugins/author-page.rb#L75 just needs to be expanded to check for external layout.
