### ISSUE TITLE
replace DAVID tool with an alternative

### ISSUE THREAD

**Issue by mfernandes61** [galaxyproject/training-material#531]
Hi,
Trying to run the ref-based RNA-seq in a GVL instance.
Can't find DAVID tool (Mentioned on page 21) in tool-shed - what should I be looking for?

TIA,
Mark

**Comment by shiltemann** [comment]
The tools seems to refer to a non-toolshed tool installed on usegalaxy.org: https://usegalaxy.org/?tool_id=hgv_david&version=1.0.1

Perhaps somebody could share the tool xml and we can see if we can turn it into a toolshed tool? (ping @nekrut)

**Comment by yvanlebras** [comment]
Hi,
After exchanging with @bgruening and @nsoranzo because I was searching for a kind of "DAVID" tool, they mention others already Galaxy integrated tools like gprofiler : https://toolshed.g2.bx.psu.edu/view/tambeta/gprofiler/dfda180ac951  / Kobas https://toolshed.g2.bx.psu.edu/view/iuc/kobas/83b998fa34ea / Goseq https://toolshed.g2.bx.psu.edu/view/iuc/goseq/9d1256d9ef0b . I think, once we have tested these 3 tools, we have to modify the DAVID mention by one (or more ?) of these tools on the tutorial...

**Comment by mvdbeek** [comment]
In any case DAVID or any other enrichment test should **absolutely not** be used with RNA-seq data without some sort of length correction. The [goseq vignette](https://www.bioconductor.org/packages/devel/bioc/vignettes/goseq/inst/doc/goseq.pdf) and paper
```
Young MD, Wakefield MJ, Smyth GK and Oshlack A (2010). “Gene ontology analysis for RNA-seq: accounting for selection bias.” Genome Biology, 11, pp. R14.
```
go into details about this (I have read other papers that reach similar conclusions, but I don't have them at hand now). Basically DAVID was developed for microarray data, where there appears to be no length bias.
