### ISSUE TITLE
RFC: removing tools.yaml files

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#768]
Wofkflow testing will use the workflow files to also install tools. We can in theory always convert a workflow to a tools files and we can install tools from a workflow file. Is there any need to store the tools.yml file anymore?

**Comment by bebatut** [comment]
We probably need the `tools.yml` file for the section in which it is installed (even if the argument is not really strong).
If we remove them, we will probably have to generate them temporarely for the annotation of the instances

**Comment by abretaud** [comment]
I find it handy to have them, I was planning to use them to keep tools up-to-date in *.genouest instances (so, using the section information too).
But I can also adapt and use the workflow file if you decide to remove them

**Comment by bebatut** [comment]
We plan to slowly remove the `tools.yaml` in favor of the workflow files alone.
We will update the scripts for annotation

**Comment by bebatut** [comment]
Discussions during the last GTN meeting #954:

- Saskia: We'll only have to consider section names, can probably use tutorial/topic name.
- Bjoern: the only reason we keep the tools.yaml is because of the section names. If we can get rid of that, then great. We could decide we don't care about sections.
- Helena: could just duplicate, have a special GTN section. Bjoern: doesn't work.
- Bjoern: we can leave in but not make it mandatory to update?
- Frederick: but then people will assume they're updated.
- No conclusion

**Comment by erasche** [comment]
Mostly done but it's the intention going forward so the RFC has been answered :)
