### ISSUE TITLE
Fill the introduction slide deck on Galaxy Introduction

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#79]
Hi,

The [introduction slide deck of Galaxy](https://github.com/bgruening/training-material/blob/master/Introduction/slides/index.html) needs to be filled.
I think it could be nice to use [ideas from this slide deck](https://github.com/bgruening/training-material/blob/master/Introduction//tmp/Introduction_to_Galaxy_Uni.pdf)

Thanks

Bérénice

**Comment by lecorguille** [comment]
ping @bebatut @shiltemann @bgruening 

Hi,

At the lab, we used to propose this Galaxy Introduction to our users:
[galaxy_initiation_corrections-1.08.pdf](http://abims.sb-roscoff.fr/sites/abims.sb-roscoff.fr/files/formation_2016/galaxy_initiation_corrections-1.08.pdf)

Before diving in the transcription of this pptx in md, I want to know your interest in it.

The outline:
- A little humoristic introduction about why they need Galaxy and what is Galaxy - slides 3-23
- How to import Data - slides 32-74
- Tool form and status - slides 75-88
- History and dataset management - slides 106-124
- Workflow - slides 125-142
- Sharing - slides 143-153

Is there already equivalent somewhere?
For you, is there any interest in push some parts of this material in the GTN repo?

We are rather hurry to have your point of view because we will propose this training soon with @loraine-gueguen. If you think that we need to ping other people to this thread feel free.

I know that it was discuted to split the training material in different small sections: https://github.com/galaxyproject/training-material/issues/198
And for sure, we need to review the different hands-on/exercice. I tried to propose exercice that are not related to the NGS field and easy to inderstand for people which are not used to handle NGS data and tool.
We also know that we will have to synchronise with those tutorials: https://github.com/galaxyproject/training-material/blob/master/Introduction/tutorials/Galaxy101-2.md

**Comment by Stortebecker** [comment]
Hi @lecorguille !

I quickly scrolled through the introduction. As you might guess, I do not like it all too much. In my opininon, the PDF is *way* too massive. A whole lot of information, but it is really hard to find the point you are looking for.

Do not get me wrong, I do not critisize the content, only the "structure", if I may call it like that. I think that this Introduction is fine for a introductory talk in a workshop, but really not as an online reference. It **is** useful for Galaxy trainers, not so much for users. 

So my advice would be to convert it into a slide deck instead and provide it for galaxy trainers. Then split it into digestable bits for users and provide these as Markdown files online, which can still be converted into PDFs, if you like it more that way.

Greetings, Florian

**Comment by Stortebecker** [comment]
@lecorguille Oh, sorry, I just saw the issue title. If you want to use this as a talk / slide deck, I am sure it will do. Maybe leave out some of the slides in the beginning. They may be nice, but there are to many of them, IMHO.

**Comment by lecorguille** [comment]
Oh, we didn't plan to convert all the material!
And indeed, it is for training purposes
And indeed, it need to be splitted

**Comment by nsoranzo** [comment]
I've also some super-basic slides I've created for a short Galaxy intro, which I was planning to contribute, you can see them at https://docs.google.com/presentation/d/10w9mvSPTdG53pMmr_u2KGF4cuKhcItFj10HRYFj1ZIw/edit?usp=sharing

**Comment by bgruening** [comment]
And here are mine if they are useful: https://github.com/bgruening/presentations/tree/master/General-Galaxy-Introduction
@lecorguille I'm pretty sure that the content of you deck will be useful all over if they are available in markdown. Maybe not as full set but partially for sure.

Thanks!

**Comment by loraine-gueguen** [comment]
Thanks for your answers! For the very next course (next week), I have not translated the slides into md, but we (with @lecorguille) will consider to do it later. 
For the hands-on, I have mirrored the tutorials https://github.com/galaxyproject/training-material/blob/master/Introduction/tutorials/Galaxy101-1.md and https://github.com/galaxyproject/training-material/blob/master/Introduction/tutorials/Galaxy101-2.md
Thanks!

**Comment by nsoranzo** [comment]
We are working on this during the Cambridge hackathon, WIP PR in https://github.com/galaxyproject/training-material/pull/313
