### ISSUE TITLE
Fill the hands-on tutorial and the slides for "Dive into quality control" and add a Galaxy tour

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#85]
Hi, 

I started to fill the [tutorial](https://github.com/bgruening/training-material/blob/master/NGS-QC/tutorials/dive_into_qc.md) and the [associated slides](https://bgruening.github.io/training-material/NGS-QC/slides/dive_into_qc.html) on Quality control, with template and idea.

We now need to fill it with a real dataset and hands-on. We can use the one from Chip-Seq or any other.

We also need to add a Galaxy tour

Thanks,

Bérénice

**Comment by yvanlebras** [comment]
Hi @bebatut, I hope all is ok for you in Auvergne ! 
Happy to have another possibility to work with you ;)
Some comments:
-It seems that the "associated slides" hyperlink is broken...
-What do you think about using MultiQC tool on this tuto and slides ? We have begin to write a interactive tour based on MultiQC

**Comment by bgruening** [comment]
Liks will be fixed during this hackathon by @Stortebecker hopefully. I like the MultiQC training addition, question for me would be if this should go into the general QC section. Ideas?

**Comment by yvanlebras** [comment]
For me this is something to consider because MultiQC is "only" focused on showing rapidly/easily "logs" / infos from each step of a workflow considering the whole datasets.... and this is so good to evaluate in few seconds quality of the entire workflow processes and its parts. ...


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Björn Grüning <notifications@github.com> 
Date : 06/10/2016  10:42  (GMT+01:00) 
À : bgruening/training-material <training-material@noreply.github.com> 
Cc : Yvan Le Bras <yvan.le_bras@irisa.fr>, Comment <comment@noreply.github.com> 
Objet : Re: [bgruening/training-material] Fill the hands-on tutorial and the slides for "Dive into quality control" and add a Galaxy tour (#85) 

Liks will be fixed during this hackathon by @Stortebecker hopefully. I like the MultiQC training addition, question for me would be if this should go into the general QC section. Ideas?

**Comment by yvanlebras** [comment]
Maybe @ewels can help us in this issue ?

**Comment by ewels** [comment]
I made a video about how to use MultiQC reports if that helps?
https://www.youtube.com/watch?v=qPbIlO_KWN0

**Comment by yvanlebras** [comment]
Anf about putting MultiQC on the general QC section for training, what's your point of view @ewels ?

**Comment by ewels** [comment]
I'm not really sure of the context here. You're talking about which [section](https://github.com/bgruening/training-material#training-material) to add MultiQC to in the Galaxy training?

I guess it depends how to write MultiQC in. It can be used with pretty much all of the different experiment types you have listed there. So you could add it to all of them and focus on interpreting the biology in the different graphs produced by the different tools, or write about it in the general section and focus on how to use MultiQC reports themselves.

**Comment by yvanlebras** [comment]
Yes, In my opinion, MultiQC is cool to exchange with trainees about NGS QC in a rapid and efficient manner...

**Comment by bebatut** [comment]
To keep an up-to-date list, I open an issue to collect tutorials needing love #807 in which I added we should add MultiQC in the tutorial.
I close this issue to limit redundancy
