### ISSUE TITLE
Open links in new window by default

### ISSUE THREAD

**Issue by frederikcoppens** [galaxyproject/training-material#912]
Links currently open in the same tab, requiring to use back button to get back to the material. Can Jekyll be configured to include target="_blank" in the link by default ?

**Comment by willdurand** [comment]
Please don't do that, if you want to open links in another tab, you can use `ctrl` (or `cmd`) + click. `target="_blank"` is not secure and not good for accessibility.

**Comment by frederikcoppens** [comment]
Indeed, wasn't aware of the security issue. This should be solved by adding `rel="noopener noreferrer"`?

Not sure what you mean with "not good for accessibility".

I expect most user will not use or even know of ctrl+click, and likely have the expectation that external links open in a new window. If implemented, it should indeed only be done for external pages.

**Comment by willdurand** [comment]
More information at: https://css-tricks.com/use-target_blank/

> I expect most user will not use or even know of ctrl+click, and likely have the expectation that external links open in a new window.

No, that's not true.

**Comment by erasche** [comment]
It'd be really nice if we had any user studies attesting to what is/isn't expected. I think my personal experience with people doing training (in my old job where I taught undergrads) is similar to what  @frederikcoppens reports, but that's just an anecdote.

When I initially read this I thought about what wikipedia does with external links, marking them with an icon. I thought then that we could mark + open external links specifically in new tabs. But this would require work to implement and I don't know of a simple way to do that.

Some cursory googling comes across a [number of](https://github.com/thebearjew/blog-posts/blob/master/2015-12-01-jekyll-external-links.md) [javascript solutions](http://fraktar.com/markdown-redcarpet-target-blank/) which I don't super love since they require running JS, but that's personal preference I suppose. Both of those look pretty easy to copy and paste if we want to try them.

**Comment by erasche** [comment]
Closed this because it has not seen activity in some time. This has been reported only by one person/group so far. Given the volume of traffic the training materials receives there is not significant support for the change at this time. If it's raised in the future and continues to be an issue let's re-open it.
