### ISSUE TITLE
GTN meeting (17th of August)

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#954]
We would like to start more regular (call) meeting of the GTN to discuss the recent changes and future directions for the Training Material.
We thought we could combine these meetings with the GTN CoFest (every 3 months on the 3rd Friday).

The first meeting will be then **next Friday (17th of August)** on [Hangout](https://hangouts.google.com/hangouts/_/calendar/Z2FsYXh5dW5pZnJlaWJ1cmdAZ21haWwuY29t.55dck65etnslp0av1tmk0hgre2?authuser=1)
For organization setup, we choose 1pm (CEST) - 7am (EST) - 9pm (AEST). *Next time, we will do it on another time zone.*

Could someone take some notes about the meeting? To have a report for anyone that can not attend. Thanks

Proposed Agenda
---

- What happen during the last months?
    - GCC: [BOF](https://github.com/galaxyproject/training-material/issues/941), Talk (blog post)
    - Work on the content and English of some tutorials
    - Restructuration of the introduction topic with 2 new topics
- Ongoing
    - Development of Planemo for training (https://github.com/galaxyproject/planemo/pull/861)
        - Creation of the skeleton of a new topic, new tutorial from workflow
        - Filling of the data library file
    - Start testing the training workflows
    - Colour for the boxes (#815)
    - Checklist for contributors (#952)
- Future direction
    - Translation
        - Example with tutorials translated into Japanese (#862)
        - More or not? How to keep up-to-date? Links to Google translate or automatic translation?
        - Submit a MozFest proposal 
    - Mentoring
        - How to do that?
        - Submit on this topic a proposal for Mozilla Open Leaders  
    - Removal of the `tools.yaml` files to use only workflow files
    - New feedback form embedded at the end of tutorials
    - Next steps at the end of tutorials
    - Metadata at the top of tutorials
    - Email address in the `CONTRIBUTORS.yaml` to ping individual people
    - Extension of Planemo for training
        - Add remaining scripts
    - Next CoFest
        - 16th of November
        - Topic? https://goo.gl/forms/d6ZZVjsWuFlEvLiL2
- Open discussions
    - GTN boundaries
    - Keep people engaged
- Other points?

    ***Feel free to add a comment here with any other point we should discuss***

**Comment by shiltemann** [comment]
Meeting Notes, thanks to @erasche :)

Thanks to everybody who participated!

## The Past Few Months

- GCC and BoF in the past months; there's an issue on giter if you want to know what happened during last meetings (https://github.com/galaxyproject/training-material/issues/941)
- people worked to simplify English of the tutorials, make it easier to under and maybe more easier to automatically translate. Not a complete process, people should continue to contribute
- New tutorials, some new topics as well, Florian is working on clip-seq
- restructuring of introduction topics, now split into three topics:
  - galaxy tips and tricks, data manipulation, user interface.
  - galaxy for scientists, how they can analyse their real data
  - Idea to focus on how to use galaxy for people who are new to it with smaller tutorials that are easier to digest.
- New theme! Let us know what you think/feedback. Tried to make them less prominent/overwhelming, so users can focus on content.
- Saskia worked on checklist for contributors. Some things you can do like trying to simplifying English, improving explanations, etc. Please review this, if there are other important things to add. In the FAQ section.

## Ongoing Work

- Numerous tutorials in progress, Single Cell RNA and Clip-Seq
- Restructuring of existing tutorials like Chip-Seq
- Working on planemo for training, adding scripts to planemo that help build tutorials, create topics, create tutorials from workflows, etc. Completely creates the workflow with datasets (from zenodo, if available), standardised formatting, standardised metadata, etc. Please test and give feedback, help identify any issues with specific workflows.
- Restructuring the metadata yaml files(?) Ref: comments from Simon on gitter. The data library script updates the metadata.yaml file.
- Script for data library, simon has opened a PR against ephemeris for taking the data library yaml format and re-creating the data library on a target galaxy. He improved ephemeris to 'sync' the data library from the local yaml file to the remote galaxy. Currently need to use `setup_data_library` with the `--legacy` flag of the ephemeris tool since the new upload API does not have the required functionality yet.
- Helena is moving metadata from the metadata.yaml file to the header of the tutorials/slides.

## Future Work

- Bjoern wants tours more prominently on the webpage. See if we can start tours directly from a tour page. (https://github.com/galaxyproject/training-material/issues/840)
- Bjoern wants to know if there are any way we can put training more prominently on usegalaxy.* welcome pages
  - Simon says highlight a training of the month in the news
  - Helena suggested putting a link in the masthead
  - Bjoern proposed post tool/workflow webhook
  - Berenice raised tweeting stuff, though this does not reach all of the audience
- Are there more general ways to push training/share that it is available? Simon: Dave can do that as well. Bjoern: we can write often to the GOBLET mailing list. Frederick: Unlikely to get traction on main ELIXIR pages, but definitely possible on ELIXIR Galaxy sub-pages
- Should we remove the tools.yaml file in lieu of the workflows? We can easily create tools.yaml from the workflows for the admins that need it using ephemeris.
  - Saskia: We'll only have to consider section names, can probably use tutorial/topic name.
  - Bjoern: the only reason we keep the tools.yaml is because of the section names. If we can get rid of that, then great. We could decide we don't care about sections.
  - Helena: could just duplicate, have a special GTN section. Bjoern: doesn't work.
  - Bjoern: we can leave in but not make it mandatory to update?
  - Frederick: but then people will assume they're updated.
  - No conclusion
- Feedback forms? Small box at the bottom with :) / :( and a short feedback form.
  - Simon: yes, good idea. Most likely to receive feedback than any other method.
- Pinging people for review
  - People don't answer GitHub pings, can we obtain their emails and then write them personal emails?
  - Bjoern: People should go to gitter and we should not single out/pinpoint special persons. If gitter is not a good enough way to get in contact with specific communities, then we need to make it more prominent.
- Translations:
  - There is an open PR for a translated tutorial. We all agree it is a good idea, but how do we deal with this? Do we keep a manual translation, do we have some that are manually done, some that are automatic/linked via google translate?
  - We submitted a proposal for MozFest for automatic translation of community documentation. We will hopefully gather ideas from the community there. But no clear solution?
  - Berenice tried to 'trick' the API to have it avoid translating specific portions of the page
  - Gildas notes that google already proposes to translate things whenever your browser is in a different language to the webpage.
  - Bjoern suggests that we add something on the template to link to the google translate URLs. We need to highlight on the front page that the current system is google translate and you should use.
- Mentorship:
  - structure to support instructors for galaxy, 1/month meeting for new instructors to give them a place to ask questions like "how can I run a workshop", to hear the recommendations we have from our experiences with various audience sizes/etc. We can also give feedback after workshops. Can we find people who are eager to mentor people?
  - Simon: we have a train the trainers session in Aus, lots of people to train with GTN material. ~60 people from across the country. They were taught how to use the training material, how to teach it. Similarly we had a small training for developers where we taught people Bioconda and tool dev. Now we're planning on having nationwide webinars for larger training sessions. You teach all the trainers in the webinars, and then everyone in their own cities gives a training. If GTN did training webinars on how to use GTN/how to get it running in galaxy, it could be useful. Will get Anna in contact with Berenice/Saskia for Aus' experiences.
- Berenice applied for Moz Open Leaders, to help with improving mentoring and train the trainers and what we can do to improve all of that.
- Simon: previously we'd discussed having 'genre' tags on tutorials, e.g. saying some tutorials are human tutorial/virus tutorial, and maybe developing 'curriculum'.
  - Berenice: improve the next steps, what tutorials can you follow this tutorial with.
  - Simon: But where to start? If you're microbial and only care about microbial stuff, then having tags for microbial or a curriculum for those users with clear entry points.
  - Berenice: can you try the tagging on one tutorial and see how it goes?
- Bjoern: any policy on `enabled: false` tutorials?
  - Simon: I want this since tools are currently in TTS
  - Berernice: When do we decide that these tutorials should be displayed? Should there be rules likes "tools should follow IUC guidelines, tools should be in MTS, etc.?"
  - Bjoern: it opens up a large can of worms but gives contributors more freedom
  - Simon: It has a valid purpose, can test it, can give trainings off of it, without tools already being complete and up to standards.
  - Bjoern: Should we have a cutoff of N months, if the tutorial isn't ready by then, remove?
  - Berenice: do we advertise that we do this? Or is it more informal?
  - Saskia: We can start informally, but there probably isn't the need to be too strict.

# Closing

Next CoFest possibly in 3 months. Should we move to the 3rd Thursday so it is easier for the Australasian region to join? Simon: Aus/Japan would much prefer Thursday. Next one will be during the BioHackathon in Paris (https://bh2018paris.info/) so some of us will be there for that.

The new topic proposals will be put on the gitter channel, please vote for them there.

**Comment by bebatut** [comment]
Thanks @erasche for the notes!

**Comment by bebatut** [comment]
The next GTN meeting should be on the 15th of November (same day as the next CoFest)
We will set up the time later
